### Задание 1

In [1]:
import numpy as np

In [9]:
x = int(input())
a = np.arange(0, x)
np.sort(a)[::-1]

12


array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### Задание 2

In [26]:
x = int(input())
a = np.arange(0, x)
mas = np.diagflat(np.sort(a)[::-1])
s = list(np.diagonal(mas, 0)) #выводим диагональ и в цикле суммируем значения
for i in s: 
    sum += i
print(sum)

4
6


### Задание 3

In [32]:
from numpy import linalg
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([[4], [12], [-3]])
print(linalg.solve(a, b))

np.allclose( np.dot(a, linalg.solve(a, b)), b )

[[ 0.46666667]
 [ 3.84444444]
 [-5.55555556]]


True

### Задание 4

In [40]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
res = 0
for i in users_stats:
    if cosine(i, next_user_stats) > res:
        res = cosine(i, next_user_stats)
print(i)

[1 0 0 2 1 4]
